from docx import Document
doc = Document()
doc.add_paragraph("Extracurricular Engineering Challenges - Application", style="Title")
doc.add_paragraph("Welcome! This form is the first step to joining an extracurricular engineering challenge. Please fill out this application individually.")
p = doc.add_paragraph()
p.add_run("IMPORTANT: You must use your official university email address. ").bold = True
p.add_run("This is mandatory so I can grant you access to the projects SharePoint and Teams workspace once the team is assembled.")
doc.add_paragraph("1. Full Name")
doc.add_paragraph("2. University Email Address (e.g., student@usj.es)")
doc.add_paragraph("3. Which project are you applying for?")
doc.add_paragraph("3D-Printed Finger-Clip Housing for Pulse Oximeter", style="List Bullet")
doc.add_paragraph("Proposing a new custom idea", style="List Bullet")
doc.add_paragraph("4. Preferred Project Role(s). Although everyone contributes to the overall goal, do you have a preference for a specific role within the team?")
doc.add_paragraph("Team Leader & Project Manager (Coordination, budget management, main contact)", style="List Bullet")
doc.add_paragraph("CAD Design & 3D Printing Specialist (Mechanical design and manufacturing)", style="List Bullet")
doc.add_paragraph("Electronics & Hardware Specialist (Circuits, sensors, and wiring)", style="List Bullet")
doc.add_paragraph("Software & Data Analyst (Coding and signal processing)", style="List Bullet")
doc.add_paragraph("Quality Assurance & Documentation (Testing protocols and technical reports)", style="List Bullet")
doc.add_paragraph("No preference / Happy to adapt", style="List Bullet")
doc.add_paragraph("5. Academic Background & Skills. Briefly list your current degree and year. Highlight any specific skills you have that are relevant to the project (e.g., CAD design, coding, electronics experience).")
doc.add_paragraph("6. Motivation. Why did you choose this specific challenge? What do you hope to learn or achieve? (Keep it brief, 2-3 sentences).")
doc.add_paragraph("7. Commitment to Autonomy")
doc.add_paragraph("I understand that this is an extracurricular challenge. I commit to being proactive, autonomous, and responsible for my tasks within the team. I understand the Project Sponsor provides high-level direction and resources, but the team drives the daily execution.", style="List Bullet")
doc.save(r"C:\Users\cpere\OneDrive - UNIVERSIDAD SAN JORGE\CPerez-Docencia\_Projects\00_Admin_Templates\Application_Form.docx")
